"""empty message

Revision ID: 556c73423843
Revises: 5b404ce4b1f9
Create Date: 2024-10-11 15:12:11.318847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556c73423843'
down_revision = '5b404ce4b1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte', schema=None) as batch_op:
        batch_op.alter_column('rib',
               existing_type=sa.VARCHAR(length=34),
               nullable=True,
               existing_server_default=sa.text("'1234'"))
        batch_op.alter_column('type_compte',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Compte Courant'"))
        batch_op.alter_column('solde_initial',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('banque',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'banque'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte', schema=None) as batch_op:
        batch_op.alter_column('banque',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'banque'"))
        batch_op.alter_column('solde_initial',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_compte',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Compte Courant'"))
        batch_op.alter_column('rib',
               existing_type=sa.VARCHAR(length=34),
               nullable=False,
               existing_server_default=sa.text("'1234'"))

    # ### end Alembic commands ###
