"""Mise à jour du modèle Compte

Revision ID: 5b404ce4b1f9
Revises: e14db5723099
Create Date: 2024-10-11 15:07:25.523770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b404ce4b1f9'
down_revision = 'e14db5723099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rib', sa.String(length=34), nullable=False, server_default='1234'))  # Valeur par défaut
        batch_op.add_column(sa.Column('type_compte', sa.String(length=50), nullable=False, server_default='Compte Courant'))  # Exemple de valeur par défaut
        batch_op.add_column(sa.Column('solde_initial', sa.Float(), nullable=False, server_default='0'))  # Valeur par défaut
        batch_op.add_column(sa.Column('banque', sa.String(length=100), nullable=False, server_default='banque'))  # Valeur par défaut

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte', schema=None) as batch_op:
        batch_op.drop_column('banque')
        batch_op.drop_column('solde_initial')
        batch_op.drop_column('type_compte')
        batch_op.drop_column('rib')

    # ### end Alembic commands ###
