"""Ajout du modèle Banque et relation avec Compte

Revision ID: 777ed990f73e
Revises: 556c73423843
Create Date: 2024-10-12 14:57:12.440881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777ed990f73e'
down_revision = '556c73423843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_compte', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('banque_id', sa.Integer(), nullable=True))
        # Ajout d'un nom pour la contrainte de clé étrangère
        batch_op.create_foreign_key('fk_compte_banque', 'banque', ['banque_id'], ['id'])
        batch_op.drop_column('banque')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compte', schema=None) as batch_op:
        # Ajout de la colonne 'banque' avec la valeur par défaut
        batch_op.add_column(sa.Column('banque', sa.VARCHAR(length=100), server_default=sa.text("'banque'"), nullable=True))
        # Ajout d'un nom pour la contrainte à supprimer
        batch_op.drop_constraint('fk_compte_banque', 'compte', type_='foreignkey')
        batch_op.drop_column('banque_id')
        batch_op.drop_column('numero_compte')

    # ### end Alembic commands ###
