"""Ajout de la colonne nature_id à ReleveCompte

Revision ID: 92d055b2a0b7
Revises: f255d8ea920e
Create Date: 2024-10-13 19:55:35.024024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d055b2a0b7'
down_revision = 'f255d8ea920e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releve_compte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nature_id', sa.Integer(), nullable=True))
        # Provide a name for the foreign key constraint
        batch_op.create_foreign_key('fk_nature_id', 'nature', ['nature_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releve_compte', schema=None) as batch_op:
        # Specify the name of the foreign key constraint to drop
        batch_op.drop_constraint('fk_nature_id', type_='foreignkey')
        batch_op.drop_column('nature_id')

    # ### end Alembic commands ###
