"""Ajout de la colonne pointage_id à Operation

Revision ID: f255d8ea920e
Revises: 777ed990f73e
Create Date: 2024-10-13 19:21:08.342358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f255d8ea920e'
down_revision = '777ed990f73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pointage_id', sa.Integer(), nullable=True))
        # Nom explicite pour la clé étrangère
        batch_op.create_foreign_key(
            'fk_operation_pointage_id',  # Nom de la contrainte
            'releve_compte',  # Table de destination
            ['pointage_id'],  # Colonne source
            ['id']  # Colonne de destination
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_operation_pointage_id', type_='foreignkey')  # Utiliser le même nom ici
        batch_op.drop_column('pointage_id')

    # ### end Alembic commands ###
